import { create } from 'zustand';

export const useLucyStore = create((set) => ({
  isOpen: false,
  open: () => set({ isOpen: true }),
  close: () => set({ isOpen: false }),
  toggle: () => set((s) => ({ isOpen: !s.isOpen })),
  messages: [],
  sessionId: null,
  voiceEnabled: true,
  isListening: false,
  isProcessing: false,
  currentSteps: [],
  pendingQuery: '',
  pendingNavigation: null,
  pendingFormPrefill: null,
  showInventoryBanner: true,
  addMessage: (msg) => set((s) => ({ messages: [...s.messages, { ...msg, id: Date.now() + Math.random() }] })),
  setProcessing: (v) => set({ isProcessing: v }),
  setListening: (v) => set({ isListening: v }),
  setSteps: (steps) => set({ currentSteps: steps }),
  setSessionId: (id) => set({ sessionId: id }),
  setPendingQuery: (q) => set({ pendingQuery: q }),
  setPendingNavigation: (nav) => set({ pendingNavigation: nav }),
  setPendingFormPrefill: (data) => set({ pendingFormPrefill: data }),
  dismissInventoryBanner: () => set({ showInventoryBanner: false }),
  reset: () => set({ messages: [], sessionId: null, currentSteps: [], pendingQuery: '', pendingNavigation: null, pendingFormPrefill: null }),
}));
